### ISSUE TITLE
Clarify minimal support rust version

### ISSUE THREAD

**Issue by WorldSEnder** [mgeisler/lipsum#83]
The recent update to 0.8.1 breaks when compiling with rust 1.56:

```
error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 3]`
   --> src/lib.rs:350:52
    |
350 |             let mut needs_cap = sentence.ends_with(punctuation);
    |                                                    ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 3]`
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 3]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 3]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 3]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 3]`
   --> src/lib.rs:362:44
    |
362 |                 needs_cap = word.ends_with(punctuation);
    |                                            ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 3]`
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 3]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 3]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 3]`

error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 3]`
   --> src/lib.rs:366:36
    |
366 |             if !sentence.ends_with(punctuation) {
    |                                    ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 3]`
    |
    = help: the trait `Fn<(char,)>` is not implemented for `[char; 3]`
    = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 3]`
    = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 3]`

For more information about this error, try `rustc --explain E0277`.
```

I'm not certain what's the underlying cause for this change (the repo is still tagged with rust 1.31, but reading #77 leads me to believe the tag is outdated). Most likely cause to me is this commit: https://github.com/mgeisler/lipsum/commit/72c48a14155b5a154812f660ef2d9ace4f160d1e

In any case, edition 2021 is part of 1.56.0 so at least that part shouldn't be an issue. Can you clarify the minimal supported compiler version, thanks :)

----

Breaking downstream CI: https://github.com/yewstack/yew/runs/6649247160?check_suite_focus=true#step:5:24

**Comment by mgeisler** [comment]
Hi @WorldSEnder,

Thanks a lot for letting me know! I had forgotten about the badge in the README! Let me clean that up ASAP...

Testing with different versions of Rust shows that [`str::ends_with`][1] works with a `&[char]` from 1.58 onwards. Testing more, shows that the problem here is the lack of an explicit type annotation. That is, this works fine on 1.56:

```rust
            let punctuation: &[char] = &['.', '!', '?'];
```

I'm not sure why, but when I compare the [1.56.1 `Pattern` page][2] with the [1.58.0 page][3], I see that it grew support for `[char; N]`. So perhaps this is what enabled the code to to compile after 1.58?

I'll fix this and push out a new release!

[1]: https://doc.rust-lang.org/nightly/std/primitive.str.html#method.ends_with
[2]: https://doc.rust-lang.org/1.56.1/std/str/pattern/trait.Pattern.html#examples
[3]: https://doc.rust-lang.org/1.58.0/std/str/pattern/trait.Pattern.html#examples

**Comment by mgeisler** [comment]
The newly released 0.8.2 version makes the library build again on 1.56.0.

I realized that I never actually answered your question about the minimum supported version: back in 2020, I stopped trying to make `lipsum` compile with Rust 1.31 (first version to suppor the 2018 edition). That happened in https://github.com/mgeisler/lipsum/commit/9d622ccd23ec0b2ae258270e244cd171290b057d, where I describe the problem a bit: repeated build failures even when nothing had changed in `lipsum`. It became frustrating to see CI fail when fixing, e.g., a totally safe thing such as a typo in the README.

So, I've been tracking the latest stable Rust release since — with no hurry to push up the required version, of course. I would be happy to try again with the 2021 edition, perhaps the Rust community have slowed down a bit so that this is feasible now. I'll try with #90 which adds Rust 1.56 to CI and then we can see how it goes.
